version: 0.2

# 

phases:
  install:
    on-failure: RETRY
    runtime-versions:
      nodejs: 20.15.1
  pre_build:
    on-failure: RETRY
    commands:
      - echo "Installing npm dependencies"
      - npm ci
      - echo "Skipping tests for now"
      #- npm test
      - echo "Logging into AWS ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - echo "Building the application"
      - npm run build
      - echo "Building the Docker image and tagging"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    on-failure: RETRY
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image to ECR"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      

#report:
#  report-tests:
#    files:
#      # location of test result output

